// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTicketBooking.Data;

#nullable disable

namespace MovieTicketBooking.Migrations
{
    [DbContext(typeof(MovieTicketBookingDbContext))]
    partial class MovieTicketBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MovieTicketBooking.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("GoldSeats")
                        .HasColumnType("int");

                    b.Property<int>("PlatinumSeats")
                        .HasColumnType("int");

                    b.Property<int>("ShowID")
                        .HasColumnType("int");

                    b.Property<int>("SilverSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BookingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ShowID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.LoginDetails", b =>
                {
                    b.Property<string>("LoginID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoginID");

                    b.ToTable("LoginDetails");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Movie", b =>
                {
                    b.Property<string>("MovieID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Duration")
                        .HasColumnType("double");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProducerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Show", b =>
                {
                    b.Property<int>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShowID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("GoldSeatRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MovieID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PlatinumSeatRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SilverSeatRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TheatreID")
                        .HasColumnType("int");

                    b.HasKey("ShowID");

                    b.HasIndex("MovieID");

                    b.HasIndex("TheatreID");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Theatre", b =>
                {
                    b.Property<int>("TheatreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TheatreID"));

                    b.Property<int>("GoldSeats")
                        .HasColumnType("int");

                    b.Property<int>("NumberofSeats")
                        .HasColumnType("int");

                    b.Property<int>("PlatinumSeats")
                        .HasColumnType("int");

                    b.Property<int>("SilverSeats")
                        .HasColumnType("int");

                    b.Property<string>("TheatreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TheatreID");

                    b.ToTable("Theatres");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Booking", b =>
                {
                    b.HasOne("MovieTicketBooking.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTicketBooking.Models.Show", "Show")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Show", b =>
                {
                    b.HasOne("MovieTicketBooking.Models.Movie", "Movie")
                        .WithMany("Shows")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTicketBooking.Models.Theatre", "Theatre")
                        .WithMany("Shows")
                        .HasForeignKey("TheatreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Movie", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Show", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieTicketBooking.Models.Theatre", b =>
                {
                    b.Navigation("Shows");
                });
#pragma warning restore 612, 618
        }
    }
}
